const config = {
  NEXT_PUBLIC_PRIVY_APP_ID: process.env.NEXT_PUBLIC_PRIVY_APP_ID,
  PRIVY_APP_SECRET: process.env.PRIVY_APP_SECRET,
  DATABASE_URL: process.env.DATABASE_URL,
  OPENFORMAT_API_KEY: process.env.OPENFORMAT_API_KEY,
  OPENFORMAT_API_URL: process.env.OPENFORMAT_API_URL,
  THIRDWEB_CLIENT_ID: process.env.THIRDWEB_CLIENT_ID,
  THIRDWEB_SECRET: process.env.THIRDWEB_SECRET,
  ACCOUNT_BALANCE_SERVICE_URL: process.env.ACCOUNT_BALANCE_SERVICE_URL,
  ACCOUNT_BALANCE_SERVICE_AUTH_TOKEN: process.env.ACCOUNT_BALANCE_SERVICE_AUTH_TOKEN,
  ACCOUNT_BALANCE_AMOUNT: process.env.ACCOUNT_BALANCE_AMOUNT,
  COMMUNITY_AGENT_AUTH_TOKEN: process.env.COMMUNITY_AGENT_AUTH_TOKEN,
  COMMUNITY_AGENT_API_URL: process.env.COMMUNITY_AGENT_API_URL,
  DISCORD_BOT_GUIDE_URL: "https://openformat.notion.site/discord-copilot-guide",
  LOW_ACTIVITY_THRESHOLD: Number.parseInt(process.env.NEXT_PUBLIC_LOW_ACTIVITY_THRESHOLD ?? "10"),
} as const;

export default config;
