const config = {
  NEXT_PUBLIC_PRIVY_APP_ID: process.env.NEXT_PUBLIC_PRIVY_APP_ID,
  PRIVY_APP_SECRET: process.env.PRIVY_APP_SECRET,
  DATABASE_URL: process.env.DATABASE_URL,
  OPENFORMAT_API_KEY: process.env.OPENFORMAT_API_KEY,
  OPENFORMAT_API_URL: process.env.OPENFORMAT_API_URL,
  THIRDWEB_CLIENT_ID: process.env.THIRDWEB_CLIENT_ID,
  THIRDWEB_SECRET: process.env.THIRDWEB_SECRET,
  ACCOUNT_BALANCE_SERVICE_URL: process.env.ACCOUNT_BALANCE_SERVICE_URL,
  ACCOUNT_BALANCE_SERVICE_AUTH_TOKEN: process.env.ACCOUNT_BALANCE_SERVICE_AUTH_TOKEN,
  ACCOUNT_BALANCE_AMOUNT: process.env.ACCOUNT_BALANCE_AMOUNT,
} as const;

export default config;
